import type { NextPage } from "next";
import { withUrqlClient } from "next-urql";
import Head from "next/head";
import React from "react";
import { useUsersQuery } from "../src/generated/graphql";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [result] = useUsersQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {result.data?.users.map((user) => {
          if (!user) return null;

          return (
            <React.Fragment key={user.id}>
              <p>id: {user.id}</p>
              <p>email: {user.email}</p>
              <p>created: {user.createdAt}</p>
              <p>updated: {user.updatedAt}</p>
            </React.Fragment>
          );
        })}
      </main>
    </div>
  );
};

export default withUrqlClient((_ssrExchange, ctx) => ({
  url: process.env.DATABASE_URL,
}))(Home);
