import React from "react";

import type { NextPage } from "next";
import Head from "next/head";
import { withUrqlClient } from "next-urql";

import { useUsersQuery } from "../src/generated/graphql";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [result] = useUsersQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Some App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <table>
          <thead>
            <tr>
              <th>Id</th>
              <th>Email</th>
              <th>created</th>
              <th>updated</th>
            </tr>
          </thead>
          <tbody>
            {result.data?.users.map(user => {
              if (!user) return null;

              return (
                <tr key={user.id}>
                  <td>{user.id}</td>
                  <td>{user.email}</td>
                  <td>{user.createdAt}</td>
                  <td>{user.updatedAt}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default withUrqlClient((_ssrExchange, ctx) => ({
  url: process.env.NEXT_PUBLIC_DATABASE_URL, //|| "http://localhost:5001/graphql",
}))(Home);
